### ISSUE TITLE
Create MultipleChoiceEnv

### ISSUE THREAD

**Issue by Chris-Carvelli** [Chris-Carvelli/ContinualLearning-ITU19#3]
# TODO
- [x] duplicate the base Minigrid env class into MinigridSomething
- [x] change the step() function so that the env runs for max_steps times
- [x] define meaningful envs that inherit from MingridSomething and return 0 or 1 if the correct choice is made
- [x] rename MinigridSomething to meaningful name
- [ ] Env with changing goal after n steps
